import { isDisabled } from '@testing-library/user-event/dist/utils';
import React, { useEffect, useRef, useState } from 'react'
import ReactSelect from 'react-select'
import makeAnimated from 'react-select/animated';

const animatedComponents = makeAnimated();

const Select = ({ options, isDisabled = true, isLoading = false, isMulti = false, placeholder = ''}) => {
    const [optionsForDb, setOptionsForDb] = useState([
        {
            "depId": 5,
            "divId": 1,
            "depName": "Кафедра математического анализа",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №3 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 6,
            "divId": 1,
            "depName": "Кафедра дискретной математики и информатики",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №3 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 7,
            "divId": 1,
            "depName": "Кафедра прикладной математики",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №3 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 9,
            "divId": 2,
            "depName": "Кафедра физической электроники",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №3 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 12,
            "divId": 2,
            "depName": "Кафедра общей физики",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №3 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 20,
            "divId": 3,
            "depName": "Кафедра физической и органической химии",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 21,
            "divId": 3,
            "depName": "Кафедра аналитической и фармацевтической химии",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 25,
            "divId": 4,
            "depName": "Кафедра ботаники",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК№4 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 26,
            "divId": 4,
            "depName": "Кафедра биохимии и биофизики",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК№4 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 27,
            "divId": 4,
            "depName": "Кафедра ихтиологии",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК№4 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 28,
            "divId": 4,
            "depName": "Кафедра почвоведения",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК№4 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 33,
            "divId": 5,
            "depName": "Кафедра русской литературы",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №2ул.Гаджиева 37",
            "forEor": null
        },
        {
            "depId": 34,
            "divId": 5,
            "depName": "Кафедра русского языка",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №2ул.Гаджиева 37",
            "forEor": null
        },
        {
            "depId": 35,
            "divId": 5,
            "depName": "Кафедра дагестанских языков",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №2ул.Гаджиева 37",
            "forEor": null
        },
        {
            "depId": 36,
            "divId": 5,
            "depName": "Кафедра литератур народов Дагестана",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №2ул.Гаджиева 37",
            "forEor": null
        },
        {
            "depId": 37,
            "divId": 5,
            "depName": "Кафедра методики преподавания русского языка и литературы",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №2ул.Гаджиева 37",
            "forEor": null
        },
        {
            "depId": 39,
            "divId": 5,
            "depName": "Кафедра теоретической и прикладной лингвистики",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №2ул.Гаджиева 37",
            "forEor": null
        },
        {
            "depId": 40,
            "divId": 5,
            "depName": "Кафедра электронных СМИ",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №2ул.Гаджиева 37",
            "forEor": null
        },
        {
            "depId": 41,
            "divId": 5,
            "depName": "Кафедра печатных СМИ",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №2ул.Гаджиева 37",
            "forEor": null
        },
        {
            "depId": 45,
            "divId": 6,
            "depName": "Кафедра всеобщей истории",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №1 ул.Коркмасова 8",
            "forEor": null
        },
        {
            "depId": 46,
            "divId": 6,
            "depName": "Кафедра истории Дагестана",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №1 ул.Коркмасова 8",
            "forEor": null
        },
        {
            "depId": 47,
            "divId": 6,
            "depName": "Кафедра отечественной истории",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №1 ул.Коркмасова 8",
            "forEor": null
        },
        {
            "depId": 48,
            "divId": 7,
            "depName": "Деканат ФИЯ",
            "depAbr": "",
            "createYear": null,
            "isMain": 1,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №2ул.Гаджиева 37",
            "forEor": null
        },
        {
            "depId": 49,
            "divId": 7,
            "depName": "Кафедра английского языка",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №2ул.Гаджиева 37",
            "forEor": null
        },
        {
            "depId": 50,
            "divId": 7,
            "depName": "Кафедра английской филологии",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №2ул.Гаджиева 37",
            "forEor": null
        },
        {
            "depId": 51,
            "divId": 7,
            "depName": "кафедра немецкого языка",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №2ул.Гаджиева 37",
            "forEor": null
        },
        {
            "depId": 52,
            "divId": 7,
            "depName": "Кафедра французского языка",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №2ул.Гаджиева 37",
            "forEor": null
        },
        {
            "depId": 53,
            "divId": 7,
            "depName": "Кафедра второго иностранного языка",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №2ул.Гаджиева 37",
            "forEor": null
        },
        {
            "depId": 56,
            "divId": 8,
            "depName": "Kафедра актерского мастерства",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "ул. Дзержинского 21",
            "forEor": null
        },
        {
            "depId": 61,
            "divId": 10,
            "depName": "Кафедра теории государства и права",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №1 ул.Коркмасова 8",
            "forEor": null
        },
        {
            "depId": 62,
            "divId": 10,
            "depName": "Кафедра истории государства и права",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №1 ул.Коркмасова 8",
            "forEor": null
        },
        {
            "depId": 66,
            "divId": 10,
            "depName": "Кафедра уголовного права и криминологии",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №1 ул.Коркмасова 8",
            "forEor": null
        },
        {
            "depId": 67,
            "divId": 10,
            "depName": "Кафедра гражданского права",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №1 ул.Коркмасова 8",
            "forEor": null
        },
        {
            "depId": 68,
            "divId": 10,
            "depName": "Кафедра уголовного процесса и криминалистики",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №1 ул.Коркмасова 8",
            "forEor": null
        },
        {
            "depId": 69,
            "divId": 10,
            "depName": "Кафедра гражданского процесса",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №1 ул.Коркмасова 8",
            "forEor": null
        },
        {
            "depId": 71,
            "divId": 10,
            "depName": "Кафедра информационного права и информатики",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №1 ул.Коркмасова 8",
            "forEor": null
        },
        {
            "depId": 73,
            "divId": 13,
            "depName": "Кафедра теории и истории социальной работы",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №11 ул.Ярагского 59 г",
            "forEor": null
        },
        {
            "depId": 76,
            "divId": 13,
            "depName": "Кафедра социальной медицины",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №11 ул.Ярагского 59 г",
            "forEor": null
        },
        {
            "depId": 77,
            "divId": 13,
            "depName": "Кафедра общей и социальной педагогики",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №11 ул.Ярагского 59 г",
            "forEor": null
        },
        {
            "depId": 79,
            "divId": 1014,
            "depName": "Кафедра геологии",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "ул.Дахадаева 21",
            "forEor": null
        },
        {
            "depId": 83,
            "divId": 1014,
            "depName": "Кафедра биологии и биоразнообразия",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "ул.Дахадаева 21",
            "forEor": null
        },
        {
            "depId": 84,
            "divId": 1014,
            "depName": "Кафедра экологии",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "ул.Дахадаева 21",
            "forEor": null
        },
        {
            "depId": 87,
            "divId": 16,
            "depName": "Кафедра арабского языка",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "ул.Дзержинского 21",
            "forEor": null
        },
        {
            "depId": 94,
            "divId": 19,
            "depName": "Деканат экономического факультета",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №4 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 99,
            "divId": 22,
            "depName": "Кафедра менеджмента",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №4 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 102,
            "divId": 22,
            "depName": "Кафедра государственного и муниципального управления",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №4 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 108,
            "divId": 19,
            "depName": "Кафедра бухгалтерского учета",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №4 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 109,
            "divId": 19,
            "depName": "Кафедра иностранных языков",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №4 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 116,
            "divId": 21,
            "depName": "Кафедра общей и социальной психологии",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №9 ул.Имама Шамиля 16 а",
            "forEor": null
        },
        {
            "depId": 117,
            "divId": 21,
            "depName": "Кафедра психологии развития и профессиональной деятельности",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №9 ул.Имама Шамиля 16 а",
            "forEor": null
        },
        {
            "depId": 119,
            "divId": 21,
            "depName": "Кафедра теории и истории религии и культуры",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №9 ул.Имама Шамиля 16 а",
            "forEor": null
        },
        {
            "depId": 120,
            "divId": 21,
            "depName": "Кафедра онтологии и теории познания",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №9 ул.Имама Шамиля 16 а",
            "forEor": null
        },
        {
            "depId": 195,
            "divId": 99,
            "depName": "Кафедра спортивных дисциплин",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 196,
            "divId": 17,
            "depName": "Кафедра физического воспитания",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 202,
            "divId": 99,
            "depName": "Кафедра физвоспитания",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "Дворец спорта",
            "forEor": null
        },
        {
            "depId": 204,
            "divId": 99,
            "depName": "Межфакультетная кафедра немецкого языка",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 208,
            "divId": 98,
            "depName": "Кафедра общеобразовательных дисциплин для иностранных граждан",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": 1,
            "isKaf": 1,
            "address": "УК № 10, Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 209,
            "divId": 98,
            "depName": "Кафедра русского языка как иностранного",
            "depAbr": "",
            "createYear": null,
            "isMain": 0,
            "dateAdd": null,
            "userLogin": "",
            "isActive": 1,
            "depType": 1,
            "isKaf": 1,
            "address": "УК № 10, Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 1255,
            "divId": 99,
            "depName": "Кафедра безопасности жизнедеятельности ",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": "2013-03-15T11:33:02.153",
            "userLogin": "null",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "ул. Дзержинского 21",
            "forEor": null
        },
        {
            "depId": 1306,
            "divId": 39,
            "depName": "Кафедра редакционно-издательского дела и информации ",
            "depAbr": "",
            "createYear": 0,
            "isMain": null,
            "dateAdd": "2013-03-28T10:07:20.547",
            "userLogin": "null",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "ул. Ярагского 59 В",
            "forEor": null
        },
        {
            "depId": 1327,
            "divId": 52,
            "depName": "Кафедра исторических и юридических дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": null,
            "dateAdd": "2013-10-17T14:08:02.183",
            "userLogin": "null",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1329,
            "divId": 8,
            "depName": "Кафедра библиотековедения и библиографии",
            "depAbr": "",
            "createYear": 0,
            "isMain": null,
            "dateAdd": "2013-10-17T16:25:49.727",
            "userLogin": "null",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1338,
            "divId": 63,
            "depName": "Кафедра гуманитарных и естественных дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": null,
            "dateAdd": "2013-11-22T15:03:02.78",
            "userLogin": "null",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1344,
            "divId": 56,
            "depName": "Кафедра общественных дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-02-03T15:00:31.92",
            "userLogin": "ok_mashidat",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1348,
            "divId": 22,
            "depName": "Кафедра \"Экономика труда и управления персоналом\"",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": "2014-03-19T09:59:05.957",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №4 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 1351,
            "divId": 56,
            "depName": "Кафедра экономических дисциплин ",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-04-09T15:52:09.85",
            "userLogin": "ok_mashidat",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1352,
            "divId": 56,
            "depName": "Кафедра юридических и экономических дисциплин ",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-04-09T15:52:24.75",
            "userLogin": "ok_mashidat",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1353,
            "divId": 56,
            "depName": "Кафедра юридических дисциплин ",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-04-09T15:52:42.847",
            "userLogin": "ok_mashidat",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1363,
            "divId": 13,
            "depName": "Кафедра социальных и информационных технологий",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": "2014-06-20T09:20:27.813",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №11 ул.Ярагского 59 г",
            "forEor": null
        },
        {
            "depId": 1364,
            "divId": 19,
            "depName": "Кафедра политической экономии",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-06-23T10:18:05.197",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №4 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 1407,
            "divId": 17,
            "depName": "Кафедра Спортивных дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-09-19T09:56:05.07",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 1432,
            "divId": 1014,
            "depName": "Кафедра Рекреационной географии и устойчивого развития",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": "2014-10-10T10:01:37.51",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "ул.Дахадаева 21",
            "forEor": null
        },
        {
            "depId": 1436,
            "divId": 86,
            "depName": "Лицей ДГУ",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": "2014-10-16T11:41:44.49",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК № 10 ул.Батырая 2/12",
            "forEor": 1
        },
        {
            "depId": 1440,
            "divId": 86,
            "depName": "Лицей ДГУ начальной школы",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": "2014-10-16T12:47:25.343",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК № 10 ул.Батырая 2/12",
            "forEor": 1
        },
        {
            "depId": 1452,
            "divId": 93,
            "depName": "Кафедра Образовательных дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-10-17T15:07:44.253",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1453,
            "divId": 92,
            "depName": "Кафедра Экономических дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-10-17T15:08:17.677",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1454,
            "divId": 95,
            "depName": "Кафедра Экономики",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-10-17T15:41:36",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1455,
            "divId": 94,
            "depName": "Кафедра Исторических и юридических дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-10-17T15:42:03.373",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1456,
            "divId": 96,
            "depName": "Кафедра Экономических дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-10-17T15:46:30.203",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1457,
            "divId": 97,
            "depName": "Кафедра Естественных и математических дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-10-17T15:47:01.993",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1458,
            "divId": 1001,
            "depName": "Кафедра Гуманитарных дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-10-17T15:47:37.547",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1459,
            "divId": 1002,
            "depName": "Кафедра Юридических дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-10-17T15:47:52.333",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1460,
            "divId": 102,
            "depName": "Кафедра Социальной работы",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-10-17T15:55:34.363",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1461,
            "divId": 100,
            "depName": "Кафедра Юридических дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-10-17T15:55:56.237",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1462,
            "divId": 101,
            "depName": "Кафедра Экономических дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2014-10-17T15:56:28.47",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1467,
            "divId": 22,
            "depName": "Кафедра \"Математическое моделирование, эконометрика и статистика\"",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": "2014-12-24T10:46:47.01",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №4 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 1476,
            "divId": 99,
            "depName": "Кафедра иностранных языков для гуманитарных факультетов",
            "depAbr": "",
            "createYear": 2015,
            "isMain": 0,
            "dateAdd": "2015-06-29T11:02:26.287",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "ул.Коркмасова 8",
            "forEor": null
        },
        {
            "depId": 1477,
            "divId": 99,
            "depName": "Кафедра иностранных языков для естественно-научных факультетов",
            "depAbr": "",
            "createYear": 2015,
            "isMain": 0,
            "dateAdd": "2015-06-29T11:03:10.073",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК № 6, Дзержинского 12",
            "forEor": null
        },
        {
            "depId": 1478,
            "divId": 1,
            "depName": "Кафедра дифференциальных уравнений и функционального анализа",
            "depAbr": "",
            "createYear": 2015,
            "isMain": 0,
            "dateAdd": "2015-06-29T11:16:55.517",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №3 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 1479,
            "divId": 21,
            "depName": "Кафедра философии и социально-политических наук",
            "depAbr": "",
            "createYear": 2015,
            "isMain": 0,
            "dateAdd": "2015-07-17T14:44:50.99",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК №9 ул.Имама Шамиля 16 а",
            "forEor": null
        },
        {
            "depId": 1480,
            "divId": 4,
            "depName": "Кафедра зоологии и физиологии",
            "depAbr": "",
            "createYear": 2015,
            "isMain": 0,
            "dateAdd": "2015-08-04T15:52:56.757",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": "УК№4 ул.Батырая 2/12",
            "forEor": null
        },
        {
            "depId": 1483,
            "divId": 108,
            "depName": "Кафедра Юридических и гуманитарных дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2015-11-11T09:39:27.637",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1484,
            "divId": 109,
            "depName": "Кафедра Экономических, естественных и математических дисциплин ",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2015-11-11T09:40:50.42",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1491,
            "divId": 112,
            "depName": "Кафедра экономических и ЕНД",
            "depAbr": "",
            "createYear": 2016,
            "isMain": 1,
            "dateAdd": "2016-04-27T10:44:39.947",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1492,
            "divId": 113,
            "depName": "Кафедра юридических дисциплин",
            "depAbr": "",
            "createYear": 2016,
            "isMain": 1,
            "dateAdd": "2016-04-27T10:45:03.48",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1497,
            "divId": 14,
            "depName": "Кафедра экологии",
            "depAbr": "",
            "createYear": 2016,
            "isMain": 1,
            "dateAdd": "2016-06-14T09:22:45.907",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1498,
            "divId": 14,
            "depName": "Кафедра геологии",
            "depAbr": "",
            "createYear": 2016,
            "isMain": 1,
            "dateAdd": "2016-06-14T09:22:55.663",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1499,
            "divId": 14,
            "depName": "Кафедра биологии и биоразнообразия",
            "depAbr": "",
            "createYear": 2016,
            "isMain": 1,
            "dateAdd": "2016-06-14T09:23:11.82",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1500,
            "divId": 14,
            "depName": "Кафедра рекреационной географии и устойчивого развития",
            "depAbr": "",
            "createYear": 2016,
            "isMain": 1,
            "dateAdd": "2016-06-14T09:23:48.36",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1502,
            "divId": 10,
            "depName": "Кафедра конституционного и международного права",
            "depAbr": "",
            "createYear": 2016,
            "isMain": 0,
            "dateAdd": "2016-07-01T12:14:04.33",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1503,
            "divId": 2,
            "depName": "Кафедра физика конденсированного состояния и наносистем",
            "depAbr": "",
            "createYear": 2016,
            "isMain": 0,
            "dateAdd": "2016-07-12T16:33:48.347",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1504,
            "divId": 23,
            "depName": "Кафедра естественно-научных и гуманитарных дисциплин",
            "depAbr": "",
            "createYear": 2016,
            "isMain": 0,
            "dateAdd": "2016-08-09T12:35:42.41",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1505,
            "divId": 23,
            "depName": "Кафедра общепрофессиональных дисциплин",
            "depAbr": "",
            "createYear": 2016,
            "isMain": 0,
            "dateAdd": "2016-08-09T12:36:10.673",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1506,
            "divId": 23,
            "depName": "Кафедра специальных дисциплин",
            "depAbr": "",
            "createYear": 2016,
            "isMain": 0,
            "dateAdd": "2016-08-09T12:36:28.957",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 1509,
            "divId": 10,
            "depName": "Кафедра административного, финансового и таможенного права",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": "2017-04-13T15:31:57.797",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2551,
            "divId": 1023,
            "depName": "Кафедра экономико-правовых и общеобразовательных дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": "2017-11-30T17:13:17.263",
            "userLogin": "pfu_main",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2560,
            "divId": 6,
            "depName": "Кафедра истории России",
            "depAbr": "",
            "createYear": 2018,
            "isMain": 0,
            "dateAdd": "2018-07-17T18:09:51.92",
            "userLogin": "begamagomed",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2561,
            "divId": 19,
            "depName": "Кафедра \"Финансы и кредит\"",
            "depAbr": "",
            "createYear": 2018,
            "isMain": 1,
            "dateAdd": "2018-07-17T18:27:19.183",
            "userLogin": "begamagomed",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2563,
            "divId": 2,
            "depName": "Кафедра инженерной физики",
            "depAbr": "",
            "createYear": 2018,
            "isMain": 0,
            "dateAdd": "2018-07-17T19:13:26.107",
            "userLogin": "begamagomed",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2564,
            "divId": 19,
            "depName": "Кафедра \"Мировая и региональная экономика\"",
            "depAbr": "",
            "createYear": 2018,
            "isMain": 1,
            "dateAdd": "2018-07-17T19:24:14.43",
            "userLogin": "begamagomed",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2566,
            "divId": 1026,
            "depName": "\tКафедра спортивных дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": "2018-10-05T21:14:42.773",
            "userLogin": "begamagomed",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2567,
            "divId": 1026,
            "depName": "Кафедра физвоспитания",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": "2018-10-05T21:15:06.09",
            "userLogin": "begamagomed",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2569,
            "divId": 22,
            "depName": "Кафедра бизнес-информатики и высшей математики",
            "depAbr": "",
            "createYear": 0,
            "isMain": 0,
            "dateAdd": "2018-10-24T13:35:56.12",
            "userLogin": "begamagomed",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2571,
            "divId": 1026,
            "depName": "Деканат",
            "depAbr": "",
            "createYear": 2018,
            "isMain": 1,
            "dateAdd": "2018-12-26T15:47:10.057",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2572,
            "divId": 1026,
            "depName": "Деканат",
            "depAbr": "",
            "createYear": 2018,
            "isMain": 1,
            "dateAdd": "2018-12-26T15:47:12.223",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2573,
            "divId": 19,
            "depName": "Компьютерный класс №3",
            "depAbr": "",
            "createYear": 2019,
            "isMain": 0,
            "dateAdd": "2019-02-07T17:46:13.03",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2575,
            "divId": 8,
            "depName": "Кафедра актерского мастерства и музыкального искусства",
            "depAbr": "",
            "createYear": 2019,
            "isMain": 1,
            "dateAdd": "2019-09-24T10:02:26.447",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2576,
            "divId": 16,
            "depName": "Кафедра востоковедения",
            "depAbr": "",
            "createYear": 2019,
            "isMain": 0,
            "dateAdd": "2019-09-25T14:41:58.733",
            "userLogin": "begamagomed",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2577,
            "divId": 20,
            "depName": "Проект Яндекс.Лицей",
            "depAbr": "",
            "createYear": 2019,
            "isMain": 1,
            "dateAdd": "2019-12-24T17:03:39.343",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2580,
            "divId": 3,
            "depName": "Кафедра \"Неорганическая химия и химическая экология\"",
            "depAbr": "",
            "createYear": 2020,
            "isMain": 1,
            "dateAdd": "2020-07-23T15:00:31.99",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2581,
            "divId": 20,
            "depName": "Кафедра \"Информационные системы и технологии программирования\"",
            "depAbr": "",
            "createYear": 2020,
            "isMain": 1,
            "dateAdd": "2020-07-29T10:26:15.73",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2582,
            "divId": 20,
            "depName": "Кафедра \"Прикладная информатика\"",
            "depAbr": "",
            "createYear": 2020,
            "isMain": 1,
            "dateAdd": "2020-07-29T10:26:52.707",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2583,
            "divId": 20,
            "depName": "Кафедра \"Информационные технологии и безопасность компьютерных систем\"",
            "depAbr": "",
            "createYear": 2020,
            "isMain": 1,
            "dateAdd": "2020-07-29T10:30:19.76",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2584,
            "divId": 1028,
            "depName": "Кафедра экономико-правовых и общеобразовательных дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2020-10-27T10:05:25.093",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2585,
            "divId": 52,
            "depName": "Кафедра экономико-правовых и общеобразовательных дисциплин",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2020-10-27T10:05:47.2",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2586,
            "divId": 1029,
            "depName": "Университетская точка кипения Дагестанского государственного университета",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2020-12-09T14:17:06.347",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2587,
            "divId": 1029,
            "depName": "Университетская точка кипения Дагестанского государственного университета",
            "depAbr": "",
            "createYear": 0,
            "isMain": 1,
            "dateAdd": "2020-12-09T14:20:31.667",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2588,
            "divId": 19,
            "depName": "Кафедра \"Экономическая безопасность, анализ и аудит\"",
            "depAbr": "",
            "createYear": 2021,
            "isMain": 1,
            "dateAdd": "2021-04-09T14:24:37.453",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2589,
            "divId": 22,
            "depName": "Кафедра \"Маркетинг и логистика\"",
            "depAbr": "",
            "createYear": 2021,
            "isMain": 0,
            "dateAdd": "2021-04-09T14:27:30.193",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2590,
            "divId": 13,
            "depName": "Кафедра общеобразовательных и профессиональных дисциплин отделения СПО",
            "depAbr": "Кафедра Ои",
            "createYear": 2021,
            "isMain": 1,
            "dateAdd": "2021-10-18T16:08:37.043",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2599,
            "divId": 2,
            "depName": "Кафедра теоретической и вычислительной физики",
            "depAbr": "",
            "createYear": 2021,
            "isMain": 0,
            "dateAdd": "2022-01-21T10:09:06.077",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2602,
            "divId": 1032,
            "depName": "Отдел по паспортно-визовой работе",
            "depAbr": "",
            "createYear": 2022,
            "isMain": 1,
            "dateAdd": "2022-03-18T15:11:24.717",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2603,
            "divId": 4,
            "depName": "Кафедра физиологии растений и биотехнологии",
            "depAbr": "",
            "createYear": 2022,
            "isMain": 0,
            "dateAdd": "2022-04-13T13:11:52.71",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        },
        {
            "depId": 2604,
            "divId": 19,
            "depName": "Кафедра экономических и финансовых исследований",
            "depAbr": "",
            "createYear": 2021,
            "isMain": 0,
            "dateAdd": "2021-04-09T14:24:37",
            "userLogin": "ok_natasha",
            "isActive": 1,
            "depType": null,
            "isKaf": 1,
            "address": null,
            "forEor": null
        }
    ])

    // const [options, setOptions] = useState([])

    // const kafedras = useRef()
    // const fillData = () => {
    //     const filterOptions = []
    //     optionsForDb.forEach(option => {    
    //         filterOptions.push({
    //             value: option.depId,
    //             label: option.depName
    //         }) 
    //     })

    //     setOptions(filterOptions)
    // }

    // useEffect(() => {
    //     fillData()
    // }, [])

    const printValue = (newValue) => {
        console.log(newValue)
    }

    return (
        <ReactSelect
            noOptionsMessage={() => 'Ничего не найдено'}              
            onChange={printValue}
            classNamePrefix={'custom-select'}
            isMulti={isMulti}
            placeholder={placeholder}
            //ref={kafedras}
            options={options}
            maxMenuHeight={280}
            components={animatedComponents}
            isDisabled={isDisabled}
            isLoading={isLoading}
        />
    )
}

export default Select;
